#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"

posteio_help_content_func() {
  declare desc="return posteio plugin help content"

  cat<<help_content
  posteio:set_domain, set the domain name for posteio
  posteio:start, start posteio container
  posteio:stop, stop posteio container
help_content
}

posteio_print_help_func() {
  declare desc="print help"

  if [[ $1 = "posteio:help" ]] ; then
    echo -e 'Usage: dokku posteio[:COMMAND]'
    posteio_help_content_func | sort | column -c2 -t -s,
  else
    posteio_help_content_func
  fi
}

case "$1" in
  help | posteio:help)
    posteio_print_help_func "$@"
    ;;
  *)
    exit "$DOKKU_NOT_IMPLEMENTED_EXIT"
    ;;
esac
