#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

restart_nginx() {
  declare desc="restart nginx for given distros"
  case "$(. /etc/os-release > /dev/null 2>&1 || true ; echo "$ID")" in
    debian)
      /usr/sbin/invoke-rc.d nginx reload > /dev/null
      ;;
    ubuntu)
      /etc/init.d/nginx reload > /dev/null
      ;;
    opensuse)
      /sbin/service nginx reload > /dev/null
      ;;
    arch|centos|rhel)
      /usr/bin/systemctl reload nginx
      ;;
  esac
}

plugin-install() {
  declare IMAGE="${POSTEIO_IMAGE}:${POSTEIO_IMAGE_VERSION}"
  if [[ "$PLUGIN_DISABLE_PULL" == "true" ]]; then
    echo " !     ${PLUGIN_DISABLE_PULL_VARIABLE} environment variable detected. Not running pull command." 1>&2
    echo " !        docker pull ${IMAGE}" 1>&2
    return
  fi
  if [[ "$(docker images -q "${IMAGE}" 2> /dev/null)" == "" ]]; then
    docker pull "${IMAGE}"
  fi

  dokku_log_info1 "Creating data directory"
  mkdir -p "${POSTEIO_ROOT}" || echo "Failed to create posteio root directory"
  chown dokku:dokku "${POSTEIO_ROOT}"

  dokku_log_info1 "Creating nginx conf directory"
  mkdir -p /etc/nginx/conf.d/ || echo "Failed to create nginx conf directory"

  dokku_log_info1 "Creating nginx conf files"
  touch "${POSTEIO_ROOT}/nginx.conf"
  echo "include ${POSTEIO_ROOT}/nginx.conf;" > /etc/nginx/conf.d/dokku_posteio.conf

  dokku_log_info1 "Restarting nginx"
  restart_nginx
}

plugin-install "$@"
