#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "${PLUGIN_CORE_AVAILABLE_PATH}/common/functions"

posteio_domain() {
  declare desc="get the current domain name for posteio"

  dokku_log_info2 "Current domain name"
  if [[ -f "${POSTEIO_ROOT}/DOMAIN" ]]; then
    cat "${POSTEIO_ROOT}/DOMAIN"
  else
    dokku_log_warn "no domain name configured, set domain name with dokku posteio:set-domain <domain>"
  fi
}

posteio_domain
