#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"

posteio_set_domain() {
  declare desc="set the domain name for posteio"
  local DOMAIN_NAME="$2"

  [[ -z "${DOMAIN_NAME}" ]] && dokku_log_fail "Please specify a domain name"
  echo "${DOMAIN_NAME}" > "${POSTEIO_ROOT}/DOMAIN"
}

posteio_set_domain "$@"
