#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "${PLUGIN_CORE_AVAILABLE_PATH}/common/functions"
source "${PLUGIN_CORE_AVAILABLE_PATH}/nginx-vhosts/functions"

posteio_stop() {
  declare desc="stops posteio container"

  if [[ -f "${POSTEIO_ROOT}/CONTAINER" ]]; then
    dokku_log_info1 "Stopping container"
    docker stop "$(< "${POSTEIO_ROOT}/CONTAINER")" || true

    dokku_log_info1 "Removing nginx config file"
    echo "" > "${POSTEIO_ROOT}/nginx.conf"
  else
    dokku_log_warn "posteio not deployed"
  fi

  restart_nginx
}

posteio_stop
