#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "${PLUGIN_CORE_AVAILABLE_PATH}/common/functions"
source "${PLUGIN_CORE_AVAILABLE_PATH}/nginx-vhosts/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

posteio_enable_ssl() {
  declare desc="toggle ssl for posteio"

  if [[ ! -f "${POSTEIO_ROOT}/SSL_IN_USE" ]]; then
    dokku_log_info1 "Enabling SSL"
    touch "${POSTEIO_ROOT}/SSL_IN_USE"
  else
    dokku_log_info1 "Disabling SSL"
    rm -f "${POSTEIO_ROOT}/SSL_IN_USE"
  fi

  if [[ -f "${POSTEIO_ROOT}/CONTAINER" ]]; then
    nginx_build_config
    restart_nginx
  fi
}

posteio_enable_ssl
